jobs:
- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true
  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - script: conda create --yes --quiet --name goldrush_edit_CI
    displayName: Create Anaconda environment
  - script: |
      source activate goldrush_edit_CI
      conda install --yes -c conda-forge mamba python=3.9
      mamba install --yes -c bioconda -c conda-forge compilers meson  boost-cpp minimap2 ntlink btllib
    displayName: Install dependencies
  - script: |
      source activate goldrush_edit_CI
      meson build --prefix=$(pwd)/test_build
      cd build
      ninja install
      ../test_build/bin/goldrush-edit --help
    displayName: Compile GoldRush-Edit
  - script: |
      source activate goldrush_edit_CI
      export PATH=$(pwd)/test_build/bin:$PATH
      cd tests
      ./goldrush_edit_test.sh
    displayName: Test run for GoldRush-Edit

- job:
  displayName: mac-latest
  pool:
    vmImage: 'macOS-latest'

  steps:
    - checkout: self
      persistCredentials: true
      submodules: true
    - script: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH
    - script: conda create --yes --quiet --name goldrush_edit_CI
      displayName: Create Anaconda environment
    - script: |
        source activate goldrush_edit_CI
        conda install --yes -c conda-forge mamba python=3.9
        mamba install --yes -c bioconda -c conda-forge compilers meson  boost-cpp minimap2 ntlink btllib
      displayName: Install dependencies
    - script: |
        source activate goldrush_edit_CI
        meson build --prefix=$(pwd)/test_build
        cd build
        ninja install
        ../test_build/bin/goldrush-edit --help
      displayName: Compile GoldRush-Edit
    - script: |
        source activate goldrush_edit_CI
        export PATH=$(pwd)/test_build/bin:$PATH
        cd tests
        ./goldrush_edit_test.sh
      displayName: Test run for GoldRush-Edit
      
