jobs:
- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true
  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - script: conda create --yes --quiet --name goldpolish_CI
    displayName: Create Anaconda environment
  - script: |
      source activate goldpolish_CI
      conda install --yes -c conda-forge mamba python=3.9
      mamba install --yes -c bioconda -c conda-forge compilers meson  boost-cpp=1.78.0 minimap2 ntlink btllib
    displayName: Install dependencies
  - script: |
      source activate goldpolish_CI
      meson build --prefix=$(pwd)/test_build
      cd build
      ninja install
      ../test_build/bin/goldpolish --help
    displayName: Compile GoldPolish
  - script: |
      source activate goldpolish_CI
      export PATH=$(pwd)/test_build/bin:$PATH
      cd tests
      ./goldpolish_test.sh
    displayName: Test run for GoldPolish

- job:
  displayName: mac-latest
  pool:
    vmImage: 'macOS-latest'

  steps:
    - checkout: self
      persistCredentials: true
      submodules: true
    - script: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH
    - script: conda create --yes --quiet --name goldpolish_CI
      displayName: Create Anaconda environment
    - script: |
        source activate goldpolish_CI
        conda install --yes -c conda-forge mamba python=3.9
        mamba install --yes -c bioconda -c conda-forge compilers meson  boost-cpp minimap2 ntlink btllib llvm
      displayName: Install dependencies
    - script: |
        source activate goldpolish_CI
        meson build --prefix=$(pwd)/test_build
        cd build
        ninja install
        ../test_build/bin/goldpolish --help
      displayName: Compile GoldPolish
    - script: |
        source activate goldpolish_CI
        export PATH=$(pwd)/test_build/bin:$PATH
        cd tests
        ./goldpolish_test.sh
      displayName: Test run for GoldPolish
      
