#!/usr/bin/env python3
import argparse
import btllib

def get_cli_args():
    parser = argparse.ArgumentParser(
        description="Convert input sequence characters to upper case."
    )
    parser.add_argument("seqs_path")
    parser.add_argument("output_path")
    return parser.parse_args()


if __name__ == "__main__":
    args = get_cli_args()

    with btllib.SeqReader(
        args.seqs_path, btllib.SeqReaderFlag.LONG_MODE
    ) as reader, btllib.SeqWriter(args.output_path) as writer:
        for record in reader:
            writer.write(record.id, record.comment, record.seq.upper(), record.qual)
