#!/urs/bin/env python3

import argparse

import btllib

def wait_on_batch(batch_confirm_pipepath):
    with open(batch_confirm_pipepath) as f:
        f.read()

def write_batch_results(tmp_dir, to_polish, writer):
    seqs_path = join(
        tmp_dir, f"{splitext(to_polish)[0]}.ntedited.prepd.sealer_scaffold.upper.fa"
    )
    if getsize(seqs_path) > 0:
        with btllib.SeqReader(seqs_path, btllib.SeqReaderFlag.LONG_MODE) as tmpreader:
            for record in tmpreader:
                writer.write(record.id, record.comment, record.seq)

shutil.rmtree(tmp_dir, ignore_errors=True)

if __name__ == "__main__":
    # bind to parent

    , btllib.SeqWriter(args.output_seqs) as writer: