#!/urs/bin/env python3

import argparse
import time

import btllib

from goldrush_edit_utils import bind_to_parent

RUSH_DELAY = 2  # Seconds

def get_cli_args():
    parser = argparse.ArgumentParser(
        "Reap the finished batches."
    )
    parser.add_argument(
        "workspace_path", help="The path to where all the polishing is taking place."
    )
    parser.add_argument(
        "prefix", help="Unique prefix of this polishing instance."
    )
    parser.add_argument(
        "output_seqs", help="Filepath to write polished seqs to."
    )  
    return parser.parse_args()

def wait_on_batch(batch_confirm_pipepath):
    with open(batch_confirm_pipepath) as f:
        f.read()

def write_batch_results(tmp_dir, to_polish, writer):
    seqs_path = join(
        tmp_dir, f"{splitext(to_polish)[0]}.ntedited.prepd.sealer_scaffold.upper.fa"
    )
    if getsize(seqs_path) > 0:
        with btllib.SeqReader(seqs_path, btllib.SeqReaderFlag.LONG_MODE) as tmpreader:
            for record in tmpreader:
                writer.write(record.id, record.comment, record.seq)

shutil.rmtree(tmp_dir, ignore_errors=True)

if __name__ == "__main__":
    args = get_cli_args()

    bind_to_parent()

    with btllib.SeqWriter(args.output_seqs) as writer:
        start_reapin()